### ISSUE TITLE
Add docker compose examples

### ISSUE THREAD

**Issue by tvelocity** [tvelocity/dockerfiles#38]
This is a popular request, e.g. in #36 where an implementation was proposed

**Comment by fspc** [comment]
There is etherpad-and-draw-node-alpine at https://github.com/fspc/etherpad-and-draw-node-alpine. The etherpad Dockerfile and entrypoint.sh is a fork of your project altered to work with alpine linux and rehashed to work with etherdraw.

**Comment by lupa18** [comment]
Hello, here a docker-compose.yml example: 
```
version: '3'

services:
  db:
    image: mariadb:latest
    restart: on-failure:5
    # to pass mariadb passords
    env_file: mariadb.env
    volumes:
      - db:/var/lib/mysql
  app:
    image: tvelocity/etherpad-lite
    restart: unless-stopped
    # to pass env variables
    env_file: etherpad.env
    ports:
      - "8080:9000"
    depends_on:
      - db

volumes:
  db:
```
